home:
    path: /
    controller: App\Controller\User\HomePageController::homePage
user_blog:
    path: /user/{id}/blog
    controller: App\Controller\User\UserBlogPageController::userBlogPage
admin:
    path: /admin
    controller: App\Controller\Admin\AdminHomePageController::adminHomePage
